# Generated by Django 4.1.7 on 2023-07-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_express_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена экспресс доставки')),
                ('edge_for_free_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Порог бесплатной доставки')),
                ('cost_usual_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена обычной доставки')),
                ('popular_products_amount', models.PositiveSmallIntegerField(default=10, verbose_name='количество популярных товаров для отображения на стартовой странице')),
                ('limited_products_amount', models.PositiveSmallIntegerField(default=5, verbose_name='количество товаров с ограниченным предложением для отображения на стартовой странице')),
                ('banners_amount', models.PositiveSmallIntegerField(default=5, verbose_name='количество баннеровдля отображения на стартовой странице')),
            ],
            options={
                'verbose_name': 'конфигурация',
                'verbose_name_plural': 'конфигурация',
            },
        ),
    ]
