# Generated by Django 4.1.7 on 2023-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма покупок')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='бесплатная доставка')),
                ('products', models.ManyToManyField(related_name='cart', to='app_catalog.product', verbose_name='товары')),
            ],
        ),
    ]
