# Generated by Django 4.1.7 on 2023-07-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_catalog', '0001_initial'),
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('express', 'Express')], default='regular', max_length=10, verbose_name='тип')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена доставки')),
            ],
            options={
                'verbose_name': 'тип доставки',
                'verbose_name_plural': 'типы доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('paymentType', models.CharField(choices=[('own online', 'Own Online'), ('someone online', 'Someone Online')], default='own online', max_length=20, verbose_name='тип оплаты')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('awaiting payment', 'Awaiting Payment'), ('paid', 'Paid'), ('delivered', 'Delivered')], default='accepted', max_length=20, verbose_name='статус платежа')),
                ('city', models.CharField(default='', max_length=40, verbose_name='город')),
                ('address', models.CharField(default='', max_length=100, verbose_name='адрес')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_account.profile', verbose_name='покупатель')),
                ('deliveryType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_orders.deliverytype', verbose_name='тип доставки')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app_orders.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товары',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='app_orders.OrderItem', to='app_catalog.product', verbose_name='товары'),
        ),
    ]
