# Generated by Django 4.1.7 on 2023-03-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_account', '0001_initial'),
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип доставки',
                'verbose_name_plural': 'типы доставки',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='название')),
            ],
            options={
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип оплаты',
                'verbose_name_plural': 'типы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма заказа')),
                ('city', models.CharField(max_length=40, verbose_name='город')),
                ('address', models.CharField(max_length=40, verbose_name='адрес')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_account.profile', verbose_name='покупатель')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_orders.deliverytype', verbose_name='тип доставки')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_orders.paymenttype', verbose_name='тип оплаты')),
                ('products', models.ManyToManyField(related_name='orders', to='app_catalog.product', verbose_name='товары')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_orders.orderstatus', verbose_name='статус заказа')),
            ],
        ),
    ]
